"""
Full AOC-4 field schema — models the complete MCA AOC-4 form (~201 items),
per AOC4_FORM_FIELDS.md (derived from a real filed form).

Each field carries a `source`:
  AUTO   — extractable from the client's financial documents (Claude/regex target)
  MANUAL — the CA/CS must type it (SRNs, product codes, service-provider info, …)
  MCA    — generated by the MCA portal itself (SRN, filing date) — never filled here

Previous-year (PY) variants for balance-sheet and P&L line items are generated
automatically (see PY generation near the bottom) as `<key>_prior_year`, matching
the Current/Previous columns on the form and the mapper's prior-year handling.
"""
from dataclasses import dataclass, field


@dataclass
class FieldDef:
    key: str
    label: str
    section: str
    data_type: str          # numeric | string | date | boolean | enum | text
    mandatory: bool
    synonyms: list[str] = field(default_factory=list)
    enum_values: list[str] | None = None
    source: str = "AUTO"     # AUTO | MANUAL | MCA
    has_prior_year: bool = False


# Ordered section keys → human labels (drives grouping in Excel + dashboard).
SECTIONS: dict[str, str] = {
    "company_identity": "Part A — Company Identity",
    "signatories": "Part A — Signatories",
    "agm": "Part A — AGM Details",
    "subsidiary": "Part A — Subsidiary / Holding",
    "auditor": "Part A — Auditor Details",
    "general_other": "Part A — General & Other Info",
    "bs_equity_liabilities": "Part B — Balance Sheet: Equity & Liabilities",
    "bs_assets": "Part B — Balance Sheet: Assets",
    "bs_breakup": "Balance Sheet — Break-up",
    "financial_parameters": "III — Financial Parameters (BS)",
    "share_capital_raised": "IV — Share Capital Raised",
    "sbn_cost": "V & VI — SBN & Cost Records",
    "pnl_revenue": "P&L — Revenue",
    "pnl_expenses": "P&L — Expenses",
    "pnl_profit": "P&L — Profit & Tax",
    "forex_params": "P&L — Forex & Parameters",
    "products_services": "IV — Principal Products/Services",
    "related_party": "Segment III — Related Party",
    "cag_report": "Segment IV — Auditor's Report / CAG",
    "csr": "Segment V — CSR",
    "misc_secretarial": "Segment VI — Misc / Secretarial Audit",
    "attachments_meta": "Attachments",
    "declaration": "Declaration",
    "certificate": "Certificate by Professional",
    "office_use": "For Office Use (MCA)",
    "prior_year": "Prior Year Comparatives",
}

_AUDIT_OPINIONS = ["unqualified", "qualified", "adverse", "disclaimer"]


BASE_FIELDS: list[FieldDef] = [
    # ── PART A: COMPANY IDENTITY (items 1-17) ────────────────────────────────
    FieldDef("cin", "Corporate Identification Number (CIN)", "company_identity", "string", True,
             ["CIN", "Corporate Identification No", "Corporate Identity Number"], source="AUTO"),
    FieldDef("authorised_capital", "Authorised capital as on date of filing", "company_identity", "numeric", False,
             ["Authorised capital", "Authorized share capital"], source="MANUAL"),
    FieldDef("number_of_members", "Number of members as on date of filing", "company_identity", "numeric", False,
             ["Number of members", "No of members"], source="MANUAL"),
    FieldDef("company_name", "Name of the company", "company_identity", "string", True,
             ["Name of Company", "Name of the company", "Company name"], source="AUTO"),
    FieldDef("registered_address", "Address of registered office", "company_identity", "text", True,
             ["Registered Office", "Address of Registered Office", "Regd. Office"], source="AUTO"),
    FieldDef("company_email", "Email ID of the company", "company_identity", "string", False,
             ["Email ID", "Email of company"], source="MANUAL"),
    FieldDef("financial_year_from", "Financial year From", "company_identity", "date", True,
             ["Financial year from", "Period from", "FY from"], source="AUTO"),
    FieldDef("financial_year_to", "Financial year To", "company_identity", "date", True,
             ["Financial year to", "Period to", "Year ended", "As at"], source="AUTO"),
    FieldDef("board_meeting_fs_date", "Date of Board meeting approving financial statements", "company_identity", "date", False,
             ["Date of board meeting", "Board meeting approving accounts", "Date of approval of financial statements"], source="AUTO"),
    FieldDef("nature_of_fs", "Nature of financial statements", "company_identity", "string", False,
             ["Nature of financial statements", "Adopted Financial statements"], source="MANUAL"),
    FieldDef("nature_of_revision", "Nature of revision", "company_identity", "string", False, source="MANUAL"),
    FieldDef("whether_provisional_fs", "Whether provisional financial statements filed earlier", "company_identity", "boolean", False, source="MANUAL"),
    FieldDef("whether_adjourned_agm", "Whether adopted in adjourned AGM", "company_identity", "boolean", False, source="MANUAL"),
    FieldDef("adjourned_agm_date", "Date of adjourned AGM", "company_identity", "date", False, source="MANUAL"),
    FieldDef("srn_inc28", "SRN of form INC-28", "company_identity", "string", False, source="MANUAL"),
    FieldDef("srn_aoc4", "SRN of form AOC-4", "company_identity", "string", False, source="MANUAL"),
    FieldDef("order_authority_date", "Date of order of competent authority", "company_identity", "date", False, source="MANUAL"),

    # ── PART A: SIGNATORIES (items 18-33) ────────────────────────────────────
    FieldDef("fs_sig1_din", "FS Signatory 1 — DIN/PAN", "signatories", "string", True,
             ["DIN", "Director Identification Number", "DIN of Director"], source="AUTO"),
    FieldDef("fs_sig1_name", "FS Signatory 1 — Name", "signatories", "string", True,
             ["Name of Director", "Signatory", "Director Name"], source="AUTO"),
    FieldDef("fs_sig1_designation", "FS Signatory 1 — Designation", "signatories", "string", False,
             ["Designation", "Director"], source="AUTO"),
    FieldDef("fs_sig1_date", "FS Signatory 1 — Date of signing", "signatories", "date", False, source="AUTO"),
    FieldDef("fs_sig2_din", "FS Signatory 2 — DIN/PAN", "signatories", "string", False, ["DIN"], source="AUTO"),
    FieldDef("fs_sig2_name", "FS Signatory 2 — Name", "signatories", "string", False, source="AUTO"),
    FieldDef("fs_sig2_designation", "FS Signatory 2 — Designation", "signatories", "string", False, source="AUTO"),
    FieldDef("fs_sig2_date", "FS Signatory 2 — Date of signing", "signatories", "date", False, source="AUTO"),
    FieldDef("board_report_date", "Date of Board meeting approving Board's report (Sec 134)", "signatories", "date", True,
             ["Date of Board Report", "Directors Report date", "Board report date"], source="AUTO"),
    FieldDef("br_sig1_din", "Board's report Signatory 1 — DIN/PAN", "signatories", "string", False, ["DIN"], source="AUTO"),
    FieldDef("br_sig1_name", "Board's report Signatory 1 — Name", "signatories", "string", False, source="AUTO"),
    FieldDef("br_sig1_designation", "Board's report Signatory 1 — Designation/Date", "signatories", "string", False, source="AUTO"),
    FieldDef("br_sig2_din", "Board's report Signatory 2 — DIN/PAN", "signatories", "string", False, ["DIN"], source="AUTO"),
    FieldDef("br_sig2_name", "Board's report Signatory 2 — Name", "signatories", "string", False, source="AUTO"),
    FieldDef("br_sig2_designation", "Board's report Signatory 2 — Designation/Date", "signatories", "string", False, source="AUTO"),
    FieldDef("auditor_report_signing_date", "Date of signing of auditors' reports", "signatories", "date", False,
             ["Date of audit report", "Date of auditors report"], source="AUTO"),

    # ── PART A: AGM (items 34-39) ────────────────────────────────────────────
    FieldDef("agm_held", "Whether AGM held", "agm", "boolean", True, ["AGM held"], source="MANUAL"),
    FieldDef("agm_date", "Date of AGM", "agm", "date", False, ["Date of AGM", "AGM date"], source="AUTO"),
    FieldDef("agm_due_date", "Due date of AGM", "agm", "date", False, source="MANUAL"),
    FieldDef("agm_extension_granted", "Whether extension for AGM granted", "agm", "boolean", False, source="MANUAL"),
    FieldDef("srn_gnl1", "SRN of GNL-1", "agm", "string", False, source="MANUAL"),
    FieldDef("agm_due_after_extension", "Due date of AGM after extension", "agm", "date", False, source="MANUAL"),

    # ── PART A: SUBSIDIARY / HOLDING (items 40-44) ───────────────────────────
    FieldDef("is_subsidiary", "Whether company is a subsidiary (clause 87)", "subsidiary", "boolean", False, source="MANUAL"),
    FieldDef("holding_company_cin", "CIN/reg number of holding company", "subsidiary", "string", False, source="MANUAL"),
    FieldDef("holding_company_name", "Name of holding company", "subsidiary", "string", False, source="MANUAL"),
    FieldDef("subsidiary_provision", "Provision under which company became subsidiary", "subsidiary", "string", False, source="MANUAL"),
    FieldDef("has_subsidiary_assoc_jv", "Whether has subsidiary/associate/JV", "subsidiary", "boolean", False, source="MANUAL"),

    # ── PART A: AUDITOR (items 45-60) ────────────────────────────────────────
    FieldDef("srn_adt1", "SRN of Form ADT-1", "auditor", "string", False, source="MANUAL"),
    FieldDef("number_of_auditors", "Number of Auditors", "auditor", "numeric", False, source="AUTO"),
    FieldDef("auditor_pan", "Income-tax PAN of auditor/firm", "auditor", "string", False, ["PAN of auditor"], source="AUTO"),
    FieldDef("auditor_category", "Category of auditor", "auditor", "enum", False,
             ["Category of auditor"], enum_values=["Individual", "Auditor's Firm"], source="AUTO"),
    FieldDef("auditor_membership_number", "Membership/registration number", "auditor", "string", False,
             ["Membership No", "Membership Number", "M. No.", "ICAI Membership No"], source="AUTO"),
    FieldDef("auditor_name", "Name of auditor/firm", "auditor", "string", False,
             ["Auditor", "Statutory auditor", "Name of auditor", "Chartered Accountants"], source="AUTO"),
    FieldDef("auditor_addr_line1", "Auditor Address Line 1", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_addr_line2", "Auditor Address Line 2", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_country", "Auditor Country", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_pincode", "Auditor Pin Code", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_area", "Auditor Area/Locality", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_city", "Auditor City", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_district", "Auditor District", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_state", "Auditor State/UT", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_member_signing_name", "Member signing — Name", "auditor", "string", False, source="AUTO"),
    FieldDef("auditor_member_signing_mno", "Member signing — Membership number", "auditor", "string", False, source="AUTO"),

    # ── PART A: GENERAL & OTHER (items 61-71) ────────────────────────────────
    FieldDef("type_of_industry", "Type of Industry", "general_other", "string", False, source="MANUAL"),
    FieldDef("schedule_iii_applicable", "Whether Schedule III applicable", "general_other", "boolean", False, source="MANUAL"),
    FieldDef("consolidated_fs_required", "Whether consolidated financial statements required", "general_other", "boolean", False, source="MANUAL"),
    FieldDef("books_electronic_form", "Whether books maintained in electronic form", "general_other", "boolean", False, source="MANUAL"),
    FieldDef("server_address", "Postal address of computer servers", "general_other", "text", False, source="MANUAL"),
    FieldDef("service_provider_name", "Name of service provider", "general_other", "string", False, source="MANUAL"),
    FieldDef("service_provider_ip", "IP address of service provider", "general_other", "string", False, source="MANUAL"),
    FieldDef("service_provider_location", "Location of service provider", "general_other", "string", False, source="MANUAL"),
    FieldDef("service_provider_cloud", "Whether maintained on cloud", "general_other", "boolean", False, source="MANUAL"),
    FieldDef("service_provider_address", "Address as provided by service provider", "general_other", "text", False, source="MANUAL"),

    # ── PART B: BALANCE SHEET — EQUITY & LIABILITIES (items 72-85) ───────────
    FieldDef("equity_share_capital", "Share capital", "bs_equity_liabilities", "numeric", True,
             ["Share Capital", "Paid up capital", "Equity share capital"], source="AUTO", has_prior_year=True),
    FieldDef("reserves_surplus", "Reserves and surplus", "bs_equity_liabilities", "numeric", True,
             ["Reserves & Surplus", "Reserves and Surplus"], source="AUTO", has_prior_year=True),
    FieldDef("money_against_warrants", "Money received against share warrants", "bs_equity_liabilities", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("share_application_money", "Share application money pending allotment", "bs_equity_liabilities", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("borrowings_noncurrent", "Long term borrowings", "bs_equity_liabilities", "numeric", False,
             ["Long term borrowings", "Term Loan"], source="AUTO", has_prior_year=True),
    FieldDef("deferred_tax_liabilities", "Deferred tax liabilities (net)", "bs_equity_liabilities", "numeric", False,
             ["DTL", "Deferred Tax Liability"], source="AUTO", has_prior_year=True),
    FieldDef("other_noncurrent_liabilities", "Other long-term liabilities", "bs_equity_liabilities", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("long_term_provisions", "Long term provisions", "bs_equity_liabilities", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("borrowings_current", "Short term borrowings", "bs_equity_liabilities", "numeric", False,
             ["Short term borrowings", "Working capital loans"], source="AUTO", has_prior_year=True),
    FieldDef("trade_payables_micro_sme", "Trade payables — dues of MSE", "bs_equity_liabilities", "numeric", False,
             ["MSME payables", "Micro and Small Enterprise payables"], source="AUTO", has_prior_year=True),
    FieldDef("trade_payables_others", "Trade payables — dues of others", "bs_equity_liabilities", "numeric", False,
             ["Trade payables others", "Creditors"], source="AUTO", has_prior_year=True),
    FieldDef("other_current_liabilities", "Other current liabilities", "bs_equity_liabilities", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("short_term_provisions", "Short term provisions", "bs_equity_liabilities", "numeric", False,
             ["Provision for tax"], source="AUTO", has_prior_year=True),
    FieldDef("total_liabilities_equity", "TOTAL EQUITY & LIABILITIES", "bs_equity_liabilities", "numeric", True,
             ["Total equity and liabilities", "TOTAL EQUITY AND LIABILITIES"], source="AUTO", has_prior_year=True),

    # ── PART B: BALANCE SHEET — ASSETS (items 86-100) ────────────────────────
    FieldDef("property_plant_equipment_net", "Property Plant and Equipment", "bs_assets", "numeric", False,
             ["PPE", "Property, Plant and Equipment", "Fixed assets", "Tangible Assets"], source="AUTO", has_prior_year=True),
    FieldDef("intangible_assets_net", "Intangible assets", "bs_assets", "numeric", False,
             ["Intangible Assets", "Goodwill"], source="AUTO", has_prior_year=True),
    FieldDef("capital_wip", "Capital work-in-progress", "bs_assets", "numeric", False,
             ["CWIP", "Capital WIP"], source="AUTO", has_prior_year=True),
    FieldDef("intangible_under_development", "Intangible assets under development", "bs_assets", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("investment_noncurrent", "Non-current Investments", "bs_assets", "numeric", False,
             ["Long term investments"], source="AUTO", has_prior_year=True),
    FieldDef("deferred_tax_assets", "Deferred tax assets (net)", "bs_assets", "numeric", False,
             ["DTA", "Deferred Tax Asset"], source="AUTO", has_prior_year=True),
    FieldDef("other_noncurrent_assets", "Long term loans and advances", "bs_assets", "numeric", False,
             ["Long-term loans and advances"], source="AUTO", has_prior_year=True),
    FieldDef("other_noncurrent_assets_misc", "Other non-current assets", "bs_assets", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("short_term_investments", "Current Investments", "bs_assets", "numeric", False,
             ["Current investments", "Short term investments"], source="AUTO", has_prior_year=True),
    FieldDef("inventories", "Inventories", "bs_assets", "numeric", False,
             ["Stock", "Inventory", "Closing Stock"], source="AUTO", has_prior_year=True),
    FieldDef("trade_receivables", "Trade receivables", "bs_assets", "numeric", False,
             ["Debtors", "Sundry Debtors", "Accounts Receivable"], source="AUTO", has_prior_year=True),
    FieldDef("cash_equivalents", "Cash and cash equivalents", "bs_assets", "numeric", False,
             ["Cash and bank", "Cash & Cash Equivalents"], source="AUTO", has_prior_year=True),
    FieldDef("loans_receivable_current", "Short term loans and advances", "bs_assets", "numeric", False,
             ["Short-term loans and advances"], source="AUTO", has_prior_year=True),
    FieldDef("other_current_assets", "Other current assets", "bs_assets", "numeric", False,
             ["Prepaid expenses"], source="AUTO", has_prior_year=True),
    FieldDef("total_assets", "TOTAL ASSETS", "bs_assets", "numeric", True,
             ["Total Assets", "TOTAL ASSETS"], source="AUTO", has_prior_year=True),

    # ── BALANCE SHEET BREAK-UP (items 101-108) ───────────────────────────────
    FieldDef("stb_from_banks", "Short-term borrowings — loans from banks", "bs_breakup", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("stb_from_others", "Short-term borrowings — loans from other parties", "bs_breakup", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("stb_total", "Total short-term borrowings", "bs_breakup", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("tr_secured", "Trade receivables — secured, considered good", "bs_breakup", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("tr_unsecured", "Trade receivables — unsecured, considered good", "bs_breakup", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("tr_doubtful", "Trade receivables — doubtful", "bs_breakup", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("tr_net", "Net trade receivables", "bs_breakup", "numeric", False,
             source="AUTO", has_prior_year=True),

    # ── III: FINANCIAL PARAMETERS (BS) (items 109-117) ───────────────────────
    FieldDef("net_worth", "Net Worth of the company", "financial_parameters", "numeric", False,
             ["Net Worth", "Shareholders funds"], source="AUTO"),
    FieldDef("shareholders_private_placement", "Shareholders under private placement", "financial_parameters", "numeric", False, source="MANUAL"),
    FieldDef("secured_loan", "Secured Loan", "financial_parameters", "numeric", False, source="AUTO"),
    FieldDef("gross_ppe_intangibles", "Gross PPE and Intangible Assets", "financial_parameters", "numeric", False,
             ["Gross block", "Gross fixed assets"], source="AUTO"),
    FieldDef("depreciation_amortization_bs", "Depreciation and amortization (BS)", "financial_parameters", "numeric", False,
             ["Accumulated depreciation"], source="AUTO"),
    FieldDef("misc_expenditure", "Misc expenditure not written off", "financial_parameters", "numeric", False, source="AUTO"),
    FieldDef("unhedged_forex", "Unhedged Foreign Exchange Exposure", "financial_parameters", "numeric", False, source="MANUAL"),
    FieldDef("operating_lease_to_financial", "Operating lease converted to financial lease", "financial_parameters", "boolean", False, source="MANUAL"),

    # ── IV: SHARE CAPITAL RAISED (items 118-122) ─────────────────────────────
    FieldDef("equity_shares_begin", "Equity shares at beginning of year (number)", "share_capital_raised", "numeric", False, source="AUTO"),
    FieldDef("equity_nominal_begin", "Equity nominal value at beginning", "share_capital_raised", "numeric", False, source="AUTO"),
    FieldDef("equity_paidup_begin", "Equity paid-up at beginning", "share_capital_raised", "numeric", False, source="AUTO"),
    FieldDef("equity_shares_end", "Equity shares at end of year (number)", "share_capital_raised", "numeric", False, source="AUTO"),
    FieldDef("equity_paidup_end", "Equity paid-up at end", "share_capital_raised", "numeric", False, source="AUTO"),
    FieldDef("preference_capital_end", "Preference share capital at end", "share_capital_raised", "numeric", False, source="AUTO"),

    # ── V & VI: SBN & COST RECORDS (items 123-126) ───────────────────────────
    FieldDef("sbn_disclosure", "Specified Bank Notes (SBN) disclosure", "sbn_cost", "text", False, source="MANUAL"),
    FieldDef("cost_records_mandated", "Whether cost records maintenance mandated", "sbn_cost", "boolean", False, source="MANUAL"),
    FieldDef("excise_tariff_heading", "Central Excise Tariff Heading", "sbn_cost", "string", False, source="MANUAL"),
    FieldDef("cost_audit_mandated", "Whether cost records audit mandated", "sbn_cost", "boolean", False, source="MANUAL"),

    # ── SEGMENT II: P&L — REVENUE (items 127-132) ────────────────────────────
    FieldDef("revenue_goods_manufactured", "Domestic — Sale of goods manufactured", "pnl_revenue", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("revenue_goods_traded", "Domestic — Sale of goods traded", "pnl_revenue", "numeric", False,
             ["Sale of traded goods"], source="AUTO", has_prior_year=True),
    FieldDef("revenue_services", "Domestic — Sale/supply of services", "pnl_revenue", "numeric", False,
             ["Sale of services", "Income from services"], source="AUTO", has_prior_year=True),
    FieldDef("revenue_from_operations", "Revenue from Operations", "pnl_revenue", "numeric", True,
             ["Turnover", "Net Sales", "Revenue from Operations", "Sales"], source="AUTO", has_prior_year=True),
    FieldDef("export_turnover", "Export turnover", "pnl_revenue", "numeric", False,
             ["Export sales"], source="AUTO", has_prior_year=True),
    FieldDef("other_income", "Other Income", "pnl_revenue", "numeric", False,
             ["Other Income", "Interest income"], source="AUTO", has_prior_year=True),
    FieldDef("total_income", "Total Income", "pnl_revenue", "numeric", True,
             ["Total Revenue", "Total Income"], source="AUTO", has_prior_year=True),

    # ── SEGMENT II: P&L — EXPENSES (items 133-144) ───────────────────────────
    FieldDef("cost_of_materials", "Cost of materials consumed", "pnl_expenses", "numeric", False,
             ["Material cost", "Raw material consumed"], source="AUTO", has_prior_year=True),
    FieldDef("purchase_stock", "Purchases of stock in trade", "pnl_expenses", "numeric", False,
             ["Purchases", "Goods purchased"], source="AUTO", has_prior_year=True),
    FieldDef("changes_inventory", "Changes in inventories", "pnl_expenses", "numeric", False,
             ["Change in stock"], source="AUTO", has_prior_year=True),
    FieldDef("employee_benefits", "Employee benefit expenses", "pnl_expenses", "numeric", False,
             ["Salaries", "Employee costs", "Staff costs", "Employee benefit expense"], source="AUTO", has_prior_year=True),
    FieldDef("managerial_remuneration", "Managerial remuneration", "pnl_expenses", "numeric", False,
             ["Director remuneration"], source="AUTO", has_prior_year=True),
    FieldDef("payment_to_auditors", "Payment to Auditors", "pnl_expenses", "numeric", False,
             ["Auditor remuneration", "Audit fees"], source="AUTO", has_prior_year=True),
    FieldDef("insurance_expenses", "Insurance expenses", "pnl_expenses", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("power_and_fuel", "Power and fuel", "pnl_expenses", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("finance_cost", "Finance cost", "pnl_expenses", "numeric", False,
             ["Interest expense", "Finance charges"], source="AUTO", has_prior_year=True),
    FieldDef("depreciation_amortization", "Depreciation and amortization", "pnl_expenses", "numeric", False,
             ["Depreciation", "D&A", "Amortization"], source="AUTO", has_prior_year=True),
    FieldDef("other_expenses", "Other expenses", "pnl_expenses", "numeric", False,
             ["Administrative expenses", "Other operating expenses"], source="AUTO", has_prior_year=True),
    FieldDef("total_expenses", "Total expenses", "pnl_expenses", "numeric", True,
             ["Total Expenses", "Total expenditure"], source="AUTO", has_prior_year=True),

    # ── SEGMENT II: P&L — PROFIT & TAX (items 145-156) ───────────────────────
    FieldDef("profit_before_exceptional", "Profit before exceptional & extraordinary items and tax", "pnl_profit", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("exceptional_items", "Exceptional items", "pnl_profit", "numeric", False,
             ["Exceptional items"], source="AUTO", has_prior_year=True),
    FieldDef("profit_before_extraordinary", "Profit before extraordinary items and tax", "pnl_profit", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("extraordinary_items", "Extraordinary items", "pnl_profit", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("profit_before_tax", "Profit before tax", "pnl_profit", "numeric", True,
             ["PBT", "Profit before taxation"], source="AUTO", has_prior_year=True),
    FieldDef("tax_expense_current", "Current tax", "pnl_profit", "numeric", False,
             ["Current tax", "Income tax"], source="AUTO", has_prior_year=True),
    FieldDef("tax_expense_deferred", "Deferred tax", "pnl_profit", "numeric", False,
             ["Deferred tax"], source="AUTO", has_prior_year=True),
    FieldDef("profit_continuing_ops", "Profit/(Loss) from continuing operations", "pnl_profit", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("profit_discontinuing_ops", "Profit/(Loss) from discontinuing operations (after tax)", "pnl_profit", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("profit_after_tax", "Profit/(Loss) for the period", "pnl_profit", "numeric", True,
             ["PAT", "Net profit", "Profit for the year", "Profit after tax"], source="AUTO", has_prior_year=True),
    FieldDef("eps_basic", "EPS before extraordinary items — Basic", "pnl_profit", "numeric", False,
             ["Basic EPS", "Basic earnings per share"], source="AUTO", has_prior_year=True),
    FieldDef("eps_diluted", "EPS before extraordinary items — Diluted", "pnl_profit", "numeric", False,
             ["Diluted EPS"], source="AUTO", has_prior_year=True),
    FieldDef("eps_basic_after", "EPS after extraordinary items — Basic", "pnl_profit", "numeric", False,
             source="AUTO", has_prior_year=True),
    FieldDef("eps_diluted_after", "EPS after extraordinary items — Diluted", "pnl_profit", "numeric", False,
             source="AUTO", has_prior_year=True),

    # ── SEGMENT II: FOREX & P&L PARAMETERS (items 157-165) ───────────────────
    FieldDef("earnings_foreign_exchange", "Earning in foreign exchange", "forex_params", "numeric", False, source="MANUAL", has_prior_year=True),
    FieldDef("expenditure_foreign_cif", "Expenditure in foreign exchange — Import CIF", "forex_params", "numeric", False, source="MANUAL", has_prior_year=True),
    FieldDef("expenditure_forex_other", "Expenditure in foreign exchange — royalty/know-how/interest", "forex_params", "numeric", False, source="MANUAL", has_prior_year=True),
    FieldDef("proposed_dividend", "Proposed Dividend", "forex_params", "numeric", False, ["Dividend"], source="AUTO", has_prior_year=True),
    FieldDef("related_party_txn_value", "AS-18 related party transaction value", "forex_params", "numeric", False, source="MANUAL"),
    FieldDef("bad_debts", "Bad debts", "forex_params", "numeric", False, source="AUTO"),
    FieldDef("political_contribution_182", "Contribution under section 182(3)", "forex_params", "numeric", False, source="MANUAL"),

    # ── SEGMENT II IV: PRINCIPAL PRODUCTS/SERVICES (items 166-172) ───────────
    FieldDef("num_product_categories", "Total number of product/service categories", "products_services", "numeric", False, source="MANUAL"),
    FieldDef("product_category_code", "Product/service category code (ITC/NPCS 4-digit)", "products_services", "string", False, source="MANUAL"),
    FieldDef("product_category_desc", "Description of category", "products_services", "text", False, source="MANUAL"),
    FieldDef("product_category_turnover", "Turnover of category", "products_services", "numeric", False, source="MANUAL"),
    FieldDef("product_highest_code", "Highest turnover contributing code (8-digit)", "products_services", "string", False, source="MANUAL"),
    FieldDef("product_highest_desc", "Description of highest product/service", "products_services", "text", False, source="MANUAL"),
    FieldDef("product_highest_turnover", "Turnover of highest contributing", "products_services", "numeric", False, source="MANUAL"),

    # ── SEGMENT III: RELATED PARTY (item 173) ────────────────────────────────
    FieldDef("has_related_party_txn", "Whether any transactions with related party", "related_party", "boolean", False,
             ["Related party transactions"], source="AUTO"),

    # ── SEGMENT IV: AUDITOR'S REPORT / CAG (items 174-177) ───────────────────
    FieldDef("audit_opinion_type", "Type of Audit Opinion", "cag_report", "enum", False,
             ["Auditor opinion", "Audit report type"], enum_values=_AUDIT_OPINIONS, source="AUTO"),
    FieldDef("cag_commented", "CAG commented/supplemented audit report", "cag_report", "string", False, source="MANUAL"),
    FieldDef("cag_supplementary_audit", "Whether CAG conducted supplementary/test audit", "cag_report", "boolean", False, source="MANUAL"),
    FieldDef("auditor_sbn_reported", "Auditors reported on SBN disclosures", "cag_report", "boolean", False, source="MANUAL"),

    # ── SEGMENT V: CSR (item 178) ────────────────────────────────────────────
    FieldDef("csr_applicable", "CSR applicability", "csr", "boolean", False,
             ["CSR", "Corporate Social Responsibility applicable"], source="AUTO"),

    # ── SEGMENT VI: MISC / SECRETARIAL AUDIT (items 179-182) ─────────────────
    FieldDef("secretarial_audit_applicable", "Whether Secretarial Audit applicable", "misc_secretarial", "boolean", False, source="MANUAL"),
    FieldDef("secretarial_audit_qualified", "Whether secretarial audit report qualified", "misc_secretarial", "boolean", False, source="MANUAL"),
    FieldDef("secretarial_observations", "Number of observations made", "misc_secretarial", "numeric", False, source="MANUAL"),
    FieldDef("secretarial_auditor_details", "Secretarial auditor details", "misc_secretarial", "text", False, source="MANUAL"),

    # ── ATTACHMENTS (items 183-189) ──────────────────────────────────────────
    FieldDef("attach_financial_statements", "Copy of financial statements (Sec 134)", "attachments_meta", "string", False, source="AUTO"),
    FieldDef("attach_supplementary_audit", "Supplementary/test audit report", "attachments_meta", "string", False, source="MANUAL"),
    FieldDef("attach_cag_comments", "Details of comments of CAG", "attachments_meta", "string", False, source="MANUAL"),
    FieldDef("attach_secretarial_audit", "Secretarial Audit Report", "attachments_meta", "string", False, source="MANUAL"),
    FieldDef("attach_reasons_not_adopting", "Reasons for not adopting financial statements", "attachments_meta", "text", False, source="MANUAL"),
    FieldDef("attach_reasons_not_agm", "Reasons for not holding AGM", "attachments_meta", "text", False, source="MANUAL"),
    FieldDef("attach_optional", "Optional attachments", "attachments_meta", "string", False, source="MANUAL"),

    # ── DECLARATION (items 190-195) ──────────────────────────────────────────
    FieldDef("board_resolution_number", "Board resolution number", "declaration", "string", False, source="MANUAL"),
    FieldDef("board_resolution_date", "Resolution date", "declaration", "date", False, source="AUTO"),
    FieldDef("declaration_signed_by", "Digitally signed by", "declaration", "string", False, source="MANUAL"),
    FieldDef("declaration_din", "DIN of signatory", "declaration", "string", False, ["DIN"], source="AUTO"),
    FieldDef("declaration_designation", "Designation", "declaration", "string", False, source="AUTO"),
    FieldDef("declaration_signer_pan", "DIN/PAN of signer", "declaration", "string", False, source="MANUAL"),

    # ── CERTIFICATE BY PRACTICING PROFESSIONAL (items 196-199) ───────────────
    FieldDef("cert_signed_by", "Certified by (CA/CS/CMA in practice)", "certificate", "string", False, source="MANUAL"),
    FieldDef("cert_associate_fellow", "Whether associate or fellow", "certificate", "enum", False,
             enum_values=["Associate", "Fellow"], source="MANUAL"),
    FieldDef("cert_membership_number", "Certifier membership number", "certificate", "string", False, source="MANUAL"),
    FieldDef("cert_cop_number", "Certificate of practice number", "certificate", "string", False, source="MANUAL"),

    # ── FOR OFFICE USE (items 200-201) — MCA generated ───────────────────────
    FieldDef("srn", "eForm Service Request Number (SRN)", "office_use", "string", False, source="MCA"),
    FieldDef("filing_date", "eForm filing date", "office_use", "date", False, source="MCA"),
]


# ── Auto-generate previous-year variants for BS/P&L line items ───────────────
def _prior_year_variants(base: list[FieldDef]) -> list[FieldDef]:
    out: list[FieldDef] = []
    for f in base:
        if not f.has_prior_year:
            continue
        out.append(FieldDef(
            key=f"{f.key}_prior_year",
            label=f"{f.label} (Previous Year)",
            section="prior_year",
            data_type=f.data_type,
            mandatory=False,
            synonyms=[f"previous year {f.label}", f"prior year {f.label}"],
            enum_values=f.enum_values,
            source=f.source,
            has_prior_year=False,
        ))
    return out


AOC4_FIELDS: list[FieldDef] = BASE_FIELDS + _prior_year_variants(BASE_FIELDS)

FIELD_BY_KEY: dict[str, FieldDef] = {f.key: f for f in AOC4_FIELDS}
MANDATORY_FIELDS: list[str] = [f.key for f in AOC4_FIELDS if f.mandatory]
AUTO_FIELD_KEYS: list[str] = [f.key for f in AOC4_FIELDS if f.source == "AUTO"]
MANUAL_FIELD_KEYS: list[str] = [f.key for f in AOC4_FIELDS if f.source == "MANUAL"]

SYNONYM_MAP: dict[str, str] = {}
for _fdef in AOC4_FIELDS:
    for _syn in _fdef.synonyms:
        SYNONYM_MAP[_syn.lower().strip()] = _fdef.key
    SYNONYM_MAP[_fdef.label.lower().strip()] = _fdef.key
